const { MsEdgeTTS, OUTPUT_FORMAT } = require('msedge-tts');
const path = require('path');
const fs = require('fs');

async function test() {
    console.log("🚀 Testing Microsoft Edge TTS...");
    const tts = new MsEdgeTTS();
    
    // Set metadata: Use ChristopherNeural for high-quality professional narration, outputting standard 24kHz Opus inside a WEBM container or MP3/WAV.
    // msedge-tts supports saving to files directly.
    const voice = 'en-US-ChristopherNeural';
    const outputFormat = OUTPUT_FORMAT.AUDIO_24KHZ_48KBITRATE_MONO_MP3;
    
    console.log(`🎙️ Voice selected: ${voice}`);
    console.log(`⚙️ Output format: ${outputFormat}`);
    
    await tts.setMetadata(voice, outputFormat);
    
    const text = "A diamond is forever. A marketing slogan so powerful it tricked the entire human race into buying common stones. This is the dark history of the De Beers empire.";
    const targetDir = path.join(__dirname, '..', 'scratch');
    
    if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
    }
    
    const targetFile = path.join(targetDir, 'edge_test_voice.mp3');
    console.log(`⏳ Synthesizing text...`);
    
    try {
        const { audioFilePath } = await tts.toFile(targetDir, text);
        console.log(`✅ Success! Audio file written to: ${audioFilePath}`);
        
        // Rename or copy to the desired file name if needed
        const defaultFilename = path.basename(audioFilePath);
        const renamedPath = path.join(targetDir, 'edge_test_voice.mp3');
        
        // msedge-tts usually writes with an autogenerated filename inside targetDir. Let's find it.
        console.log(`Original file path: ${audioFilePath}`);
        if (fs.existsSync(audioFilePath)) {
            fs.renameSync(audioFilePath, renamedPath);
            console.log(`🎉 Audio renamed to: ${renamedPath}`);
        }
    } catch (err) {
        console.error("🔴 Error generating TTS:", err.message);
    }
}

test().catch(console.error);
