window.SAINTS_PRAYER_COMPANIONS = window.SAINTS_PRAYER_COMPANIONS || {};
window.SAINTS_PRAYER_COMPANIONS[20] = {
  "video": {
    "title": "Akathist of Repentance | Prayer With Text and Icon",
    "channel": "The Saints",
    "type": "prayer_companion",
    "status": "rights_verified"
  },
  "rights_verified": true,
  "source_notes": [
    {
      "title": "Akathist Hymn of Repentance in Christ",
      "url": "https://www.sumarokovomp.ru/spravochnik/pravoslavny-molitvoslov/molitvyi-na-anglijskom-grecheskom-latyini-azerbajdzhanskom-i-tatarskom/molitvyi-na-anglijskom-yazyike/akathist-hymn-of-repentance-in-christ",
      "use": "Public domain English translation sourced from Podvorye of Novospassky Monastery in Sumarokovo."
    }
  ],
  "voice_policy": {
    "preferred": "Use a permissioned real Orthodox priest, monk, deacon, chanter, or reader recording if available.",
    "fallback": "Use an original non-impersonating narration voice.",
    "blocked": "Do not clone or imitate a real priest or monk without explicit consent.",
    "allowed_fallback": true,
    "audio_leads": []
  },
  "pastoral_context": {
    "helps_with": [
      "sincere repentance",
      "overcoming pride and self-display",
      "seeking spiritual sobriety",
      "struggling with passions",
      "courage in times of persecution",
      "pitying and forgiving others"
    ],
    "disclaimer": "This prayer companion is not a promise of a specific outcome and does not replace pastoral, medical, or professional help."
  },
  "sections": [
    {
      "section_id": "opening",
      "title": "Before We Pray",
      "voiceover": "Hegumen Nikon Vorobiev was a modern elder and teacher of repentance. Since he is not formally canonized, there is no official Akathist hymn dedicated to him. In keeping with his teachings, this prayer companion presents the Akathist of Repentance. It is offered as a way to pray for mercy, sobriety, humility, and the recovery of truth before God.",
      "screen_text": "Akathist of Repentance\nPray slowly. Read with attention."
    },
    {
      "section_id": "kontakion_1",
      "title": "Kontakion 1",
      "voiceover": "Christ our Savior, we bring supplication and praise to You as we heed the call to repentance of sins. Grant us the wisdom to listen to Your teachings according to the Scriptures, especially from that moment forward when You said, “Repent, for the Kingdom of Heaven is at hand.” Guide us to understand all things pertaining to repentance. In recognition of Your divine message and Your entire ministry on earth, we implore You:\nChrist our Savior, save us.",
      "screen_text": "Christ our Savior, we bring supplication and praise to You as we heed the call to repentance of sins. Grant us the wisdom to listen to Your teachings according to the Scriptures, especially from that moment forward when You said, “Repent, for the Kingdom of Heaven is at hand.” Guide us to understand all things pertaining to repentance. In recognition of Your divine message and Your entire ministry on earth, we implore You:\nChrist our Savior, save us."
    },
    {
      "section_id": "ikos_1",
      "title": "Ikos 1",
      "voiceover": "The Forerunner and Baptist John preached in the wilderness of Judea. Many people from the region came to hear him say, “Prepare the way of the Lord; make His paths straight.” You also came from Galilee to be baptized, Lord Jesus, even though You had no need of repentance. The Heavenly Father then said of You, “This is My beloved Son in Whom I am well pleased.” Both the newly baptized and the yet unbaptized therefore sang praises to You:\nSave us, Only-Begotten Son of God Who was sent into the world to redeem mankind.\nSave us, Son of the Virgin Who freely offers forgiveness of sins to all.\nSave us, Jesus Christ Who was baptized in the Jordan River by Saint John the Baptist.\nSave us, Savior Who never sinned but fulfilled all righteousness.\nSave us, for we have heard the holy preaching and we are born of water and of the Spirit.\nSave us, for we desire salvation and a virtuous life.\nSave us, for the heavens rejoice when a sinner repents.\nSave us, for the Kingdom of Heaven is near.\nSave us, for we repent daily and prepare a way for You, Lord Jesus.\nSave us, for we continually make our path straight for You, Immortal One.\nSave us and make us worthy of the Holy Spirit dwelling in us.\nSave us and make us heirs of the Heavenly Kingdom.\nChrist our Savior, save us.",
      "screen_text": "The Forerunner and Baptist John preached in the wilderness of Judea. Many people from the region came to hear him say, “Prepare the way of the Lord; make His paths straight.” You also came from Galilee to be baptized, Lord Jesus, even though You had no need of repentance. The Heavenly Father then said of You, “This is My beloved Son in Whom I am well pleased.” Both the newly baptized and the yet unbaptized therefore sang praises to You:\nSave us, Only-Begotten Son of God Who was sent into the world to redeem mankind.\nSave us, Son of the Virgin Who freely offers forgiveness of sins to all.\nSave us, Jesus Christ Who was baptized in the Jordan River by Saint John the Baptist.\nSave us, Savior Who never sinned but fulfilled all righteousness.\nSave us, for we have heard the holy preaching and we are born of water and of the Spirit.\nSave us, for we desire salvation and a virtuous life.\nSave us, for the heavens rejoice when a sinner repents.\nSave us, for the Kingdom of Heaven is near.\nSave us, for we repent daily and prepare a way for You, Lord Jesus.\nSave us, for we continually make our path straight for You, Immortal One.\nSave us and make us worthy of the Holy Spirit dwelling in us.\nSave us and make us heirs of the Heavenly Kingdom.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_2",
      "title": "Kontakion 2",
      "voiceover": "You called forth the fisherman, Peter, to follow You and become a fisher of men. Peter immediately left his nets and became Your devoted disciple. However, on that difficult day when you were betrayed and arrested, Peter’s faith was shaken and he quickly denied You three times. Afterwards, Peter repented and fixed his heart on God, crying: Alleluia.",
      "screen_text": "You called forth the fisherman, Peter, to follow You and become a fisher of men. Peter immediately left his nets and became Your devoted disciple. However, on that difficult day when you were betrayed and arrested, Peter’s faith was shaken and he quickly denied You three times. Afterwards, Peter repented and fixed his heart on God, crying: Alleluia."
    },
    {
      "section_id": "ikos_2",
      "title": "Ikos 2",
      "voiceover": "Lord Jesus, You know the heart of every sinner and You invite penitents to an eternal life of peace, joy and love. Peter recognized the inadequacy of his own feelings of loyalty, and learned that all strength is bestowed through the grace of God. Thereafter understanding that God can perform wondrous works through the weaknesses of the repentant, the holy Apostle sang praises such as these:\nSave us, for we believe that You are the Christ Who has come into the world to save sinners.\nSave us, for we shall not be afraid to confess You before unbelievers.\nSave us, for the wages of sin is death.\nSave us, for in the Name of Jesus Christ is forgiveness of sins and life everlasting.\nSave us, for we confess our trespasses and we forgive those who trespass against us.\nSave us, for only You can create in us a pure heart.\nSave us, for we have sinned against God and against the human race.\nSave us, for we reject our evil ways which separated us from God and caused strife with one another.\nSave us, by being born again we become the children of God.\nSave us, by Your death on the Cross, You release us from the bondage of passions and the dominion of death.\nSave us, together with Saint Peter we beseech divine mercy upon our weaknesses.\nSave us, together with all the saints we despise sin and desire the virtues.\nChrist our Savior, save us.",
      "screen_text": "Lord Jesus, You know the heart of every sinner and You invite penitents to an eternal life of peace, joy and love. Peter recognized the inadequacy of his own feelings of loyalty, and learned that all strength is bestowed through the grace of God. Thereafter understanding that God can perform wondrous works through the weaknesses of the repentant, the holy Apostle sang praises such as these:\nSave us, for we believe that You are the Christ Who has come into the world to save sinners.\nSave us, for we shall not be afraid to confess You before unbelievers.\nSave us, for the wages of sin is death.\nSave us, for in the Name of Jesus Christ is forgiveness of sins and life everlasting.\nSave us, for we confess our trespasses and we forgive those who trespass against us.\nSave us, for only You can create in us a pure heart.\nSave us, for we have sinned against God and against the human race.\nSave us, for we reject our evil ways which separated us from God and caused strife with one another.\nSave us, by being born again we become the children of God.\nSave us, by Your death on the Cross, You release us from the bondage of passions and the dominion of death.\nSave us, together with Saint Peter we beseech divine mercy upon our weaknesses.\nSave us, together with all the saints we despise sin and desire the virtues.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_3",
      "title": "Kontakion 3",
      "voiceover": "When the Galileans were slaughtered by Pilate, during a religious ceremony, eighteen bystanders were accidentally killed when a tower fell on them. Using this tragedy to call people to repentance, Jesus, You said, “Do you suppose that these Galileans were worse sinners than all other Galileans, because they suffered such things? I tell you, no; but unless you repent you will all likewise perish.” Then all the people present said: Alleluia.",
      "screen_text": "When the Galileans were slaughtered by Pilate, during a religious ceremony, eighteen bystanders were accidentally killed when a tower fell on them. Using this tragedy to call people to repentance, Jesus, You said, “Do you suppose that these Galileans were worse sinners than all other Galileans, because they suffered such things? I tell you, no; but unless you repent you will all likewise perish.” Then all the people present said: Alleluia."
    },
    {
      "section_id": "ikos_3",
      "title": "Ikos 3",
      "voiceover": "Everyone is called to repentance without delay, for death can come unexpectedly to the virtuous and the sinful alike. Without a change of heart today, we will not be prepared to face the Judgment Day. Come then, let us repent unceasingly until we depart from this life, rightfully chanting praises to Christ our God:\nSave us, for all have sinned in thought, word and deed.\nSave us, for we are saturated with worldly pleasures.\nSave us, for we succumb to conformity with the world.\nSave us, for the world welcomes our downfall.\nSave us, for we are faithless in prayer and worship.\nSave us, for we look down at the troubled sea.\nSave us, for we repent and then turn back to our old ways.\nSave us, for we ascend the ladder and then fall into the abyss.\nSave us, for we are unstable in our emotions.\nSave us, for we are enslaved to past turmoil.\nSave us, for we covet glory for ourselves.\nSave us, for we water the weeds of pride and vanity.\nSave us, for we serve Satan in many subtle ways.\nSave us, for we are not vigilant day and night.\nChrist our Savior, save us.",
      "screen_text": "Everyone is called to repentance without delay, for death can come unexpectedly to the virtuous and the sinful alike. Without a change of heart today, we will not be prepared to face the Judgment Day. Come then, let us repent unceasingly until we depart from this life, rightfully chanting praises to Christ our God:\nSave us, for all have sinned in thought, word and deed.\nSave us, for we are saturated with worldly pleasures.\nSave us, for we succumb to conformity with the world.\nSave us, for the world welcomes our downfall.\nSave us, for we are faithless in prayer and worship.\nSave us, for we look down at the troubled sea.\nSave us, for we repent and then turn back to our old ways.\nSave us, for we ascend the ladder and then fall into the abyss.\nSave us, for we are unstable in our emotions.\nSave us, for we are enslaved to past turmoil.\nSave us, for we covet glory for ourselves.\nSave us, for we water the weeds of pride and vanity.\nSave us, for we serve Satan in many subtle ways.\nSave us, for we are not vigilant day and night.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_4",
      "title": "Kontakion 4",
      "voiceover": "Mary Magdalene came to the tomb in the early morning hours, seeking the Sun that was to rise over the world. She wept as she looked down at the tomb, for she had also been at the Cross, and she loved You dearly. In Your great mercy, Lord Jesus, You appeared to her and spoke her name, “Mary!” Then with great joy she ran to the disciples and announced the astonishing news, shouting: Alleluia.",
      "screen_text": "Mary Magdalene came to the tomb in the early morning hours, seeking the Sun that was to rise over the world. She wept as she looked down at the tomb, for she had also been at the Cross, and she loved You dearly. In Your great mercy, Lord Jesus, You appeared to her and spoke her name, “Mary!” Then with great joy she ran to the disciples and announced the astonishing news, shouting: Alleluia."
    },
    {
      "section_id": "ikos_4",
      "title": "Ikos 4",
      "voiceover": "Speak our names also, Christ God, and call us out of the darkness of sin and into the radiant light of repentance. Lift us from the dread of death to the vista of Christian renewal, since we have renounced all worldly ways and wish to be filled with faith, hope and charity. Thereby released from the tomb of our own making, we may cry out in gratitude:\nSave us, that we may walk forward in the True Faith.\nSave us, that we may render all glory to God.\nSave us, that we may live in obedience to His divine will.\nSave us, that we may fulfill the teachings of the Scriptures.\nSave us, that we may joyfully mourn for our sins.\nSave us, that we may be comforted by the Holy Spirit.\nSave us, that we may behold the beauty of the Theotokos.\nSave us, that she may find in us a heart that loves her Son.\nSave us, that we may learn the right path from Mary Magdalene.\nSave us, that she may pray for us in times of tribulation.\nSave us, that we may be a blessing to others.\nSave us, that they may see the image of God in us.\nChrist our Savior, save us.",
      "screen_text": "Speak our names also, Christ God, and call us out of the darkness of sin and into the radiant light of repentance. Lift us from the dread of death to the vista of Christian renewal, since we have renounced all worldly ways and wish to be filled with faith, hope and charity. Thereby released from the tomb of our own making, we may cry out in gratitude:\nSave us, that we may walk forward in the True Faith.\nSave us, that we may render all glory to God.\nSave us, that we may live in obedience to His divine will.\nSave us, that we may fulfill the teachings of the Scriptures.\nSave us, that we may joyfully mourn for our sins.\nSave us, that we may be comforted by the Holy Spirit.\nSave us, that we may behold the beauty of the Theotokos.\nSave us, that she may find in us a heart that loves her Son.\nSave us, that we may learn the right path from Mary Magdalene.\nSave us, that she may pray for us in times of tribulation.\nSave us, that we may be a blessing to others.\nSave us, that they may see the image of God in us.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_5",
      "title": "Kontakion 5",
      "voiceover": "The righteous Job seemed to suffer unfairly, having lived according to the ways of God all his life. Yet, Job never complained but only sought a deeper understanding of God. Job realized that mere human explanations for his condition were inadequate, and he replied to the Almighty and Sovereign God, “Therefore I abhor myself, and repent in dust and ashes.” Receiving a renewal of humility and trust, he then said: Alleluia.",
      "screen_text": "The righteous Job seemed to suffer unfairly, having lived according to the ways of God all his life. Yet, Job never complained but only sought a deeper understanding of God. Job realized that mere human explanations for his condition were inadequate, and he replied to the Almighty and Sovereign God, “Therefore I abhor myself, and repent in dust and ashes.” Receiving a renewal of humility and trust, he then said: Alleluia."
    },
    {
      "section_id": "ikos_5",
      "title": "Ikos 5",
      "voiceover": "Only through repentance can we begin to understand our troubles on earth and the nature of God in Heaven. Even then, we can never fully know the mind of God, and He is not obliged to defend His actions to His creatures. Let us therefore bow down in humility, and trust in His divine wisdom with praises such as these:\nSave us from the devil.\nSave us from death.\nSave us from worldly explanations.\nSave us from insufficient philosophies.\nSave us from false authority.\nSave us from false humility.\nSave us from sinful habits.\nSave us from impure passions.\nSave us from our transgressions.\nSave us from our disobedience.\nSave us from self-indulgence.\nSave us from self-justification.\nChrist our Savior, save us.",
      "screen_text": "Only through repentance can we begin to understand our troubles on earth and the nature of God in Heaven. Even then, we can never fully know the mind of God, and He is not obliged to defend His actions to His creatures. Let us therefore bow down in humility, and trust in His divine wisdom with praises such as these:\nSave us from the devil.\nSave us from death.\nSave us from worldly explanations.\nSave us from insufficient philosophies.\nSave us from false authority.\nSave us from false humility.\nSave us from sinful habits.\nSave us from impure passions.\nSave us from our transgressions.\nSave us from our disobedience.\nSave us from self-indulgence.\nSave us from self-justification.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_6",
      "title": "Kontakion 6",
      "voiceover": "We see that Jesus Christ revealed Himself to Saul when, on a journey to Damascus, a light shone around him from Heaven. Saul heard a voice say, “I am Jesus Whom you are persecuting.” In that moment, with trembling, Saul asked, “What do You want me to do?” He who persecuted Christians then converted to Christianity, repenting always and pleasing You in all things, Lord Jesus, and saying to all the nations: Alleluia.",
      "screen_text": "We see that Jesus Christ revealed Himself to Saul when, on a journey to Damascus, a light shone around him from Heaven. Saul heard a voice say, “I am Jesus Whom you are persecuting.” In that moment, with trembling, Saul asked, “What do You want me to do?” He who persecuted Christians then converted to Christianity, repenting always and pleasing You in all things, Lord Jesus, and saying to all the nations: Alleluia."
    },
    {
      "section_id": "ikos_6",
      "title": "Ikos 6",
      "voiceover": "Christ our Savior, the message of repentance was heard and then preached by the Apostle Paul who accepted You as the Savior of the whole world. He taught many people that You are the Way, the Truth, and the Life, so that all may sing supplications and praises in this manner:\nSave us, Holy Trinity, for we are baptized in the Name of the Father and of the Son and of the Holy Spirit.\nSave us, Almighty God, for You are all-knowing and all-powerful.\nSave us, Jesus Christ, for You are all-merciful and all-innocent.\nSave us, Holy Spirit, for You dwell in us.\nSave us, Theotokos, for you are the Mother of the Incarnate God and you are our Mediatress.\nSave us, Saint Paul, for you became all things to all men.\nSave us, Lord Jesus, for we detest evil and turn to do good.\nSave us, for we wish to do only what is pleasing to You.\nSave us, for we make no excuses for our sins.\nSave us, for we desire a renewed mind and a pure heart.\nSave us, for we are followers of the True Way.\nSave us, for we submit to Your teachings.\nChrist our Savior, save us.",
      "screen_text": "Christ our Savior, the message of repentance was heard and then preached by the Apostle Paul who accepted You as the Savior of the whole world. He taught many people that You are the Way, the Truth, and the Life, so that all may sing supplications and praises in this manner:\nSave us, Holy Trinity, for we are baptized in the Name of the Father and of the Son and of the Holy Spirit.\nSave us, Almighty God, for You are all-knowing and all-powerful.\nSave us, Jesus Christ, for You are all-merciful and all-innocent.\nSave us, Holy Spirit, for You dwell in us.\nSave us, Theotokos, for you are the Mother of the Incarnate God and you are our Mediatress.\nSave us, Saint Paul, for you became all things to all men.\nSave us, Lord Jesus, for we detest evil and turn to do good.\nSave us, for we wish to do only what is pleasing to You.\nSave us, for we make no excuses for our sins.\nSave us, for we desire a renewed mind and a pure heart.\nSave us, for we are followers of the True Way.\nSave us, for we submit to Your teachings.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_7",
      "title": "Kontakion 7",
      "voiceover": "Let us reconcile with God and with one another, confessing our sins and asking forgiveness. Let us not hesitate but respond immediately to Christ God Who said, “For I did not come to call the righteous, but sinners, to repentance.” If we repent, then the depth of our sinfulness will only indicate the greater depth of Christ’s love for mankind. Let us love the One Who first loved us and say to one another: Alleluia.",
      "screen_text": "Let us reconcile with God and with one another, confessing our sins and asking forgiveness. Let us not hesitate but respond immediately to Christ God Who said, “For I did not come to call the righteous, but sinners, to repentance.” If we repent, then the depth of our sinfulness will only indicate the greater depth of Christ’s love for mankind. Let us love the One Who first loved us and say to one another: Alleluia."
    },
    {
      "section_id": "ikos_7",
      "title": "Ikos 7",
      "voiceover": "Who is the first among sinners? It is I, for I can repent only of my own sins. I cannot judge my brother or condemn my sister, but I can only turn from my own sins and bring forth good fruit as evidence of my repentance. Therefore, let us have sympathy for one another and sing praises in unity:\nSave us and call forth all the nations to repentance.\nSave us and call forth all the kings and queens and presidents.\nSave us and call the fishermen and the shepherds.\nSave us and call the tax-collectors and the prostitutes.\nSave us and call the theologians and the teachers.\nSave us and call the servants and the slaves.\nSave us and call the righteous with the sinners.\nSave us and call the poor with the rich.\nSave us and call the monks and nuns into the chapel.\nSave us and call the hermits into the caves.\nSave us and call the priests to the altar.\nSave us and call the congregation to Confession.\nChrist our Savior, save us.",
      "screen_text": "Who is the first among sinners? It is I, for I can repent only of my own sins. I cannot judge my brother or condemn my sister, but I can only turn from my own sins and bring forth good fruit as evidence of my repentance. Therefore, let us have sympathy for one another and sing praises in unity:\nSave us and call forth all the nations to repentance.\nSave us and call forth all the kings and queens and presidents.\nSave us and call the fishermen and the shepherds.\nSave us and call the tax-collectors and the prostitutes.\nSave us and call the theologians and the teachers.\nSave us and call the servants and the slaves.\nSave us and call the righteous with the sinners.\nSave us and call the poor with the rich.\nSave us and call the monks and nuns into the chapel.\nSave us and call the hermits into the caves.\nSave us and call the priests to the altar.\nSave us and call the congregation to Confession.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_8",
      "title": "Kontakion 8",
      "voiceover": "The good thief immediately repented when he beheld the goodness of Christ on the Cross. His name was Dismas and he said, “Lord, remember me when You come into Your Kingdom.” You assured him, Jesus, that today he would be with You in Paradise, and he cried out: Alleluia.",
      "screen_text": "The good thief immediately repented when he beheld the goodness of Christ on the Cross. His name was Dismas and he said, “Lord, remember me when You come into Your Kingdom.” You assured him, Jesus, that today he would be with You in Paradise, and he cried out: Alleluia."
    },
    {
      "section_id": "ikos_8",
      "title": "Ikos 8",
      "voiceover": "Grant that we may also be with You, Lord Jesus, today and forever, on earth and in Heaven, for You have always been there for us even though we failed to discern Your goodness and Your innocent suffering on our behalf. Accept our repentance as You accepted Dismas who turned his eyes toward You in complete trust. We are all criminals deserving punishment, but in faith we offer these praises:\nSave us, for You are the Crucified Christ.\nSave us, for You are the joy of Great Lent.\nSave us, for we wish to die in a repentant state.\nSave us, for we hope to be worthy of everlasting life.\nSave us, for we pray for undeserved kindness.\nSave us, for we yearn to know the True God.\nSave us, for You are our Advocate with the Father.\nSave us, for You desire that none should be lost.\nSave us, for the way of the world leads to destruction.\nSave us, for the way of the Cross pours out forgiveness.\nSave us, for this world will pass away.\nSave us, for the Kingdom is eternal.\nChrist our Savior, save us.",
      "screen_text": "Grant that we may also be with You, Lord Jesus, today and forever, on earth and in Heaven, for You have always been there for us even though we failed to discern Your goodness and Your innocent suffering on our behalf. Accept our repentance as You accepted Dismas who turned his eyes toward You in complete trust. We are all criminals deserving punishment, but in faith we offer these praises:\nSave us, for You are the Crucified Christ.\nSave us, for You are the joy of Great Lent.\nSave us, for we wish to die in a repentant state.\nSave us, for we hope to be worthy of everlasting life.\nSave us, for we pray for undeserved kindness.\nSave us, for we yearn to know the True God.\nSave us, for You are our Advocate with the Father.\nSave us, for You desire that none should be lost.\nSave us, for the way of the world leads to destruction.\nSave us, for the way of the Cross pours out forgiveness.\nSave us, for this world will pass away.\nSave us, for the Kingdom is eternal.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_9",
      "title": "Kontakion 9",
      "voiceover": "Poor Adam and Eve, for they sinned and did not repent. They did not take responsibility for their disobedience — but Adam blamed Eve, and Eve blamed the serpent. To this day, we blame others when we act upon our secret desires and transgress against God. However, it is not too late for us to turn to Christ Who, through obedience to the Father, overcame the serpent and restored Adam that we may all say: Alleluia.",
      "screen_text": "Poor Adam and Eve, for they sinned and did not repent. They did not take responsibility for their disobedience — but Adam blamed Eve, and Eve blamed the serpent. To this day, we blame others when we act upon our secret desires and transgress against God. However, it is not too late for us to turn to Christ Who, through obedience to the Father, overcame the serpent and restored Adam that we may all say: Alleluia."
    },
    {
      "section_id": "ikos_9",
      "title": "Ikos 9",
      "voiceover": "In his refusal to repent of a promise gone wrong, Herod Antipas executed Saint John the Baptist whom he had already imprisoned. He who preached repentance was beheaded by him who preferred to please sinners and to abuse his position for malicious conduct. Christ our Savior, grant us the sense to turn away from the example of Herod and return to the preaching of the martyred John, repenting and chanting praises:\nSave us, for we are easily deceived and befuddled.\nSave us, for we fear the opinion of the world.\nSave us, for we want things that are not good for us.\nSave us, for we are attracted to demonic influences.\nSave us, for we think we can hide our sins from God.\nSave us, for we do not want our evil deeds exposed.\nSave us, for we are envious of those who do good.\nSave us, for we resent those who resist the devil.\nSave us, for we are comfortable with the hideous.\nSave us, for we are no longer shocked by sin.\nSave us, for we will disobey unless You obstruct our way.\nSave us, for we will perish unless You restore us to life.\nChrist our Savior, save us.",
      "screen_text": "In his refusal to repent of a promise gone wrong, Herod Antipas executed Saint John the Baptist whom he had already imprisoned. He who preached repentance was beheaded by him who preferred to please sinners and to abuse his position for malicious conduct. Christ our Savior, grant us the sense to turn away from the example of Herod and return to the preaching of the martyred John, repenting and chanting praises:\nSave us, for we are easily deceived and befuddled.\nSave us, for we fear the opinion of the world.\nSave us, for we want things that are not good for us.\nSave us, for we are attracted to demonic influences.\nSave us, for we think we can hide our sins from God.\nSave us, for we do not want our evil deeds exposed.\nSave us, for we are envious of those who do good.\nSave us, for we resent those who resist the devil.\nSave us, for we are comfortable with the hideous.\nSave us, for we are no longer shocked by sin.\nSave us, for we will disobey unless You obstruct our way.\nSave us, for we will perish unless You restore us to life.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_10",
      "title": "Kontakion 10",
      "voiceover": "Lord Jesus, this is what You taught the people. “And this is the will of Him Who sent Me, that everyone who sees the Son and believes in Him may have everlasting life; and I will raise him up at the last day.” We do see You, Jesus, Son of God, and we repent before You, and when we repent we see You more clearly. In this way, we deepen our faith daily and say: Alleluia.",
      "screen_text": "Lord Jesus, this is what You taught the people. “And this is the will of Him Who sent Me, that everyone who sees the Son and believes in Him may have everlasting life; and I will raise him up at the last day.” We do see You, Jesus, Son of God, and we repent before You, and when we repent we see You more clearly. In this way, we deepen our faith daily and say: Alleluia."
    },
    {
      "section_id": "ikos_10",
      "title": "Ikos 10",
      "voiceover": "We look only to You, Christ God, for it is the will of the Father that we know the Scriptures. We thereby behold Your wondrous works and perfect teachings, and we believe in You. The way of sin often seems right, but the consequence is always destruction. Only Your Way transforms us into children of light, walking on the road of righteousness and singing praises such as these:\nSave us and make us alive in God.\nSave us and make us instruments of His love.\nSave us and set us free from wrongdoing.\nSave us and grant us the gift of eternal life.\nSave us and raise us up from the dead.\nSave us and put to death our evil deeds.\nSave us and find us worthy of Your compassion.\nSave us and have mercy upon whomever You will.\nSave us and help our unbelief.\nSave us and increase our faith.\nSave us and make us glad in truth.\nSave us and make us wise in thought.\nChrist our Savior, save us.",
      "screen_text": "We look only to You, Christ God, for it is the will of the Father that we know the Scriptures. We thereby behold Your wondrous works and perfect teachings, and we believe in You. The way of sin often seems right, but the consequence is always destruction. Only Your Way transforms us into children of light, walking on the road of righteousness and singing praises such as these:\nSave us and make us alive in God.\nSave us and make us instruments of His love.\nSave us and set us free from wrongdoing.\nSave us and grant us the gift of eternal life.\nSave us and raise us up from the dead.\nSave us and put to death our evil deeds.\nSave us and find us worthy of Your compassion.\nSave us and have mercy upon whomever You will.\nSave us and help our unbelief.\nSave us and increase our faith.\nSave us and make us glad in truth.\nSave us and make us wise in thought.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_11",
      "title": "Kontakion 11",
      "voiceover": "The Prodigal Son committed many outward sins, but repented inwardly with his whole heart and soul when he said, “Father, I have sinned against Heaven and in your sight, and am no longer worthy to be called your son.” The father, overjoyed at the son’s return and moved by his humility and remorse, quickly forgave him and said: Alleluia.",
      "screen_text": "The Prodigal Son committed many outward sins, but repented inwardly with his whole heart and soul when he said, “Father, I have sinned against Heaven and in your sight, and am no longer worthy to be called your son.” The father, overjoyed at the son’s return and moved by his humility and remorse, quickly forgave him and said: Alleluia."
    },
    {
      "section_id": "ikos_11",
      "title": "Ikos 11",
      "voiceover": "If we likewise repent, brothers and sisters, our Father in Heaven will greet us and reinstate us to the stature of obedient children and the heirs of His riches. He sent His Only-Begotten Son, Jesus Christ, to save us from sin, for He so loved us and wanted us to have eternal life. For this reason, we sing praises with thanksgiving:\nSave us and forgive us for every transgression.\nSave us and receive us as prodigal sons and daughters.\nSave us, for we have squandered our potential.\nSave us, for we have disrespected Your tender mercy.\nSave us, for we have wasted the wealth of Christianity.\nSave us, for we have disregarded the Crucifixion.\nSave us and protect us on the path to the virtues.\nSave us and guard us from the lure of wrongdoing.\nSave us and nourish us with the teachings of the Scriptures.\nSave us and strengthen us with the writings of the saints.\nSave us, for we are restored to new life.\nSave us, for it is right to be glad.\nChrist our Savior, save us.",
      "screen_text": "If we likewise repent, brothers and sisters, our Father in Heaven will greet us and reinstate us to the stature of obedient children and the heirs of His riches. He sent His Only-Begotten Son, Jesus Christ, to save us from sin, for He so loved us and wanted us to have eternal life. For this reason, we sing praises with thanksgiving:\nSave us and forgive us for every transgression.\nSave us and receive us as prodigal sons and daughters.\nSave us, for we have squandered our potential.\nSave us, for we have disrespected Your tender mercy.\nSave us, for we have wasted the wealth of Christianity.\nSave us, for we have disregarded the Crucifixion.\nSave us and protect us on the path to the virtues.\nSave us and guard us from the lure of wrongdoing.\nSave us and nourish us with the teachings of the Scriptures.\nSave us and strengthen us with the writings of the saints.\nSave us, for we are restored to new life.\nSave us, for it is right to be glad.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_12",
      "title": "Kontakion 12",
      "voiceover": "We see that Jesus Christ, John the Baptist, Peter and Paul went forth and preached repentance. They understood that preaching, and therefore the Gospel, is for the purpose of fulfillment of salvation and not for empty talk and vain arguments. Christ is risen and is living, and He is the Lord to Whom we joyfully say: Alleluia.",
      "screen_text": "We see that Jesus Christ, John the Baptist, Peter and Paul went forth and preached repentance. They understood that preaching, and therefore the Gospel, is for the purpose of fulfillment of salvation and not for empty talk and vain arguments. Christ is risen and is living, and He is the Lord to Whom we joyfully say: Alleluia."
    },
    {
      "section_id": "ikos_12",
      "title": "Ikos 12",
      "voiceover": "We have heard the preaching, Lord Jesus, and we believe and repent. We shall bring forth fruit worthy of repentance, each in our own way and according to the will of God. We die to sin in order to live for You, unceasingly offering praises:\nSave us, Divine preacher.\nSave us, patient teacher.\nSave us, submissive Son.\nSave us, merciful Master.\nSave us, sublime wisdom.\nSave us, perfect goodness.\nSave us, forgiver of debts.\nSave us, absolver of iniquities.\nSave us, reconciler of sinners.\nSave us, Advocate for penitents.\nSave us, receiver of prodigals.\nSave us, rewarder of believers.\nChrist our Savior, save us.",
      "screen_text": "We have heard the preaching, Lord Jesus, and we believe and repent. We shall bring forth fruit worthy of repentance, each in our own way and according to the will of God. We die to sin in order to live for You, unceasingly offering praises:\nSave us, Divine preacher.\nSave us, patient teacher.\nSave us, submissive Son.\nSave us, merciful Master.\nSave us, sublime wisdom.\nSave us, perfect goodness.\nSave us, forgiver of debts.\nSave us, absolver of iniquities.\nSave us, reconciler of sinners.\nSave us, Advocate for penitents.\nSave us, receiver of prodigals.\nSave us, rewarder of believers.\nChrist our Savior, save us."
    },
    {
      "section_id": "kontakion_13",
      "title": "Kontakion 13",
      "voiceover": "Let the unbaptized come forward and be baptized. Let the baptized move upward in continual repentance for transgressions committed after Baptism. Let us all renew our trust and acquire humility. May we deepen our faith day by day in prayer. May we not take lightly our deliverance, but accept responsibility for our deeds and thank Christ our Savior for His immeasurable compassion, saying: Alleluia. Alleluia. Alleluia.\n\n(Repeat Kontakion 13 three times.)",
      "screen_text": "Let the unbaptized come forward and be baptized. Let the baptized move upward in continual repentance for transgressions committed after Baptism. Let us all renew our trust and acquire humility. May we deepen our faith day by day in prayer. May we not take lightly our deliverance, but accept responsibility for our deeds and thank Christ our Savior for His immeasurable compassion, saying: Alleluia. Alleluia. Alleluia.\n\n(Repeat Kontakion 13 three times.)"
    },
    {
      "section_id": "kontakion_1_repeated",
      "title": "Kontakion 1 (repeated)",
      "voiceover": "Christ our Savior, we bring supplication and praise to You as we heed the call to repentance of sins. Grant us the wisdom to listen to Your teachings according to the Scriptures, especially from that moment forward when You said, “Repent, for the Kingdom of Heaven is at hand.” Guide us to understand all things pertaining to repentance. In recognition of Your divine message and Your entire ministry on earth, we implore You:\nChrist our Savior, save us.",
      "screen_text": "Christ our Savior, we bring supplication and praise to You as we heed the call to repentance of sins. Grant us the wisdom to listen to Your teachings according to the Scriptures, especially from that moment forward when You said, “Repent, for the Kingdom of Heaven is at hand.” Guide us to understand all things pertaining to repentance. In recognition of Your divine message and Your entire ministry on earth, we implore You:\nChrist our Savior, save us."
    },
    {
      "section_id": "ikos_1_repeated",
      "title": "Ikos 1 (repeated)",
      "voiceover": "The Forerunner and Baptist John preached in the wilderness of Judea. Many people from the region came to hear him say, “Prepare the way of the Lord; make His paths straight.” You also came from Galilee to be baptized, Lord Jesus, even though You had no need of repentance. The Heavenly Father then said of You, “This is My beloved Son in Whom I am well pleased.” Both the newly baptized and the yet unbaptized therefore sang praises to You:\nSave us, Only-Begotten Son of God Who was sent into the world to redeem mankind.\nSave us, Son of the Virgin Who freely offers forgiveness of sins to all.\nSave us, Jesus Christ Who was baptized in the Jordan River by Saint John the Baptist.\nSave us, Savior Who never sinned but fulfilled all righteousness.\nSave us, for we have heard the holy preaching and we are born of water and of the Spirit.\nSave us, for we desire salvation and a virtuous life.\nSave us, for the heavens rejoice when a sinner repents.\nSave us, for the Kingdom of Heaven is near.\nSave us, for we repent daily and prepare a way for You, Lord Jesus.\nSave us, for we continually make our path straight for You, Immortal One.\nSave us and make us worthy of the Holy Spirit dwelling in us.\nSave us and make us heirs of the Heavenly Kingdom.\nChrist our Savior, save us.",
      "screen_text": "The Forerunner and Baptist John preached in the wilderness of Judea. Many people from the region came to hear him say, “Prepare the way of the Lord; make His paths straight.” You also came from Galilee to be baptized, Lord Jesus, even though You had no need of repentance. The Heavenly Father then said of You, “This is My beloved Son in Whom I am well pleased.” Both the newly baptized and the yet unbaptized therefore sang praises to You:\nSave us, Only-Begotten Son of God Who was sent into the world to redeem mankind.\nSave us, Son of the Virgin Who freely offers forgiveness of sins to all.\nSave us, Jesus Christ Who was baptized in the Jordan River by Saint John the Baptist.\nSave us, Savior Who never sinned but fulfilled all righteousness.\nSave us, for we have heard the holy preaching and we are born of water and of the Spirit.\nSave us, for we desire salvation and a virtuous life.\nSave us, for the heavens rejoice when a sinner repents.\nSave us, for the Kingdom of Heaven is near.\nSave us, for we repent daily and prepare a way for You, Lord Jesus.\nSave us, for we continually make our path straight for You, Immortal One.\nSave us and make us worthy of the Holy Spirit dwelling in us.\nSave us and make us heirs of the Heavenly Kingdom.\nChrist our Savior, save us."
    },
    {
      "section_id": "a_prayer",
      "title": "A Prayer",
      "voiceover": "Hear our prayer, Jesus Christ, for our sins have wrought ruin upon us and we seek restoration and reconciliation. We can hardly speak, for our transgressions are countless and Your innocence is brighter than a white cloud. The origins of all our wrongdoings are pride, vanity, greed, jealousy, ambition, bitterness and every other passion of our fallen condition. Forgive us, Christ our Savior, for everything. Restore us in every way that we may also thank You for everything and for everyone. Thank You for letting us see our own sins, that we may repent of them now and be found worthy though unworthy of eternal life. All that we ask is to do what is pleasing to God from this day forward. Amen.",
      "screen_text": "Hear our prayer, Jesus Christ, for our sins have wrought ruin upon us and we seek restoration and reconciliation. We can hardly speak, for our transgressions are countless and Your innocence is brighter than a white cloud. The origins of all our wrongdoings are pride, vanity, greed, jealousy, ambition, bitterness and every other passion of our fallen condition. Forgive us, Christ our Savior, for everything. Restore us in every way that we may also thank You for everything and for everyone. Thank You for letting us see our own sins, that we may repent of them now and be found worthy though unworthy of eternal life. All that we ask is to do what is pleasing to God from this day forward. Amen."
    },
    {
      "section_id": "closing",
      "title": "Closing",
      "voiceover": "Lord Jesus Christ, Son of God, have mercy on us and grant us a sincere, humble heart of repentance. Amen.",
      "screen_text": "Lord Jesus Christ, have mercy on me, a sinner."
    }
  ],
  "visual_style": {
    "primary_image": "verified portrait of Hegumen Nikon Vorobiev",
    "text_layout": "large centered prayer text with icon present on screen",
    "mobile_rule": "text must remain readable on phones"
  }
};
