#!/usr/bin/env bash
# Auto-generated by shorts_extractor.js — video 1
# Estimated hook start: ~0s | estimated duration: ~58s
# Adjust -ss and -t if the actual voiceover timecodes differ

FFMPEG="ffmpeg"

"$FFMPEG" \
  -ss 0 \
  -i "videos\uploaded\FINAL_VIDEO_1_VISUAL_UPGRADE.mp4" \
  -t 58 \
  -vf "crop=608:1080:(iw-608)/2:0,scale=1080:1920:flags=lanczos" \
  -c:v libx264 -preset fast -crf 18 \
  -c:a aac -b:a 128k \
  -movflags +faststart \
  "metadata/shorts/video_1_short.mp4"

echo "Short written to metadata/shorts/video_1_short.mp4"