<# Clean Saints beat-card generator. #>
param([string]$VideoId)
$ErrorActionPreference='Stop'; if(-not $VideoId){throw 'Usage: powershell -File automation\saints_visual_polish_agent.ps1 <id>'}
Add-Type -AssemblyName System.Drawing
$repoRoot=Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..'); $root=Join-Path $repoRoot 'The Saints'; $assetDir=Join-Path $root "assets\saints_video_${VideoId}_assets"; $planFile=Join-Path $assetDir 'visual_plan.json'; if(-not(Test-Path $planFile)){throw "Missing visual plan: $planFile"}
$plan=Get-Content -Encoding UTF8 -LiteralPath $planFile -Raw | ConvertFrom-Json; $realDir=Join-Path $assetDir 'real_sources'; $portraits=@(); if(Test-Path $realDir){$portraits=@(Get-ChildItem -LiteralPath $realDir -File|Where-Object{$_.Extension -match '\.(jpg|jpeg|png)$'}|Select-Object -ExpandProperty FullName)}
if($portraits.Count -lt 1){throw "Missing required saint/elder image source in $realDir. Saints videos must show the saint/elder picture; abstract fallback cards are not allowed."}
function Shorten([string]$t,[int]$m){if(-not$t){return''};$c=($t-replace'\s+',' ').Trim();if($c.Length-le$m){return $c};return $c.Substring(0,$m).Trim()+'...'}
function DrawWrapped($g,[string]$text,$font,$brush,[single]$x,[single]$y,[int]$maxChars,[int]$lineHeight,[int]$maxLines){$words=($text-split'\s+')|Where-Object{$_};$lines=New-Object System.Collections.Generic.List[string];$line='';foreach($word in $words){$try=if($line){"$line $word"}else{$word};if($try.Length-gt$maxChars -and $line){$lines.Add($line);$line=$word}else{$line=$try}};if($line){$lines.Add($line)};for($i=0;$i-lt[Math]::Min($lines.Count,$maxLines);$i++){$g.DrawString($lines[$i],$font,$brush,$x,$y+($i*$lineHeight))}}
function NewCard([string]$out,[string]$title,[string]$sub,[string]$footer,[string]$portrait,[int]$variant){if(-not $portrait -or -not(Test-Path $portrait)){throw "Missing required saint/elder portrait while rendering $out"};$bmp=[System.Drawing.Bitmap]::new(1920,1080);$g=[System.Drawing.Graphics]::FromImage($bmp);$g.SmoothingMode='HighQuality';$g.TextRenderingHint='AntiAliasGridFit';$g.Clear([System.Drawing.Color]::FromArgb(14,11,17));$panel=[System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(36,26,24,29));$gold=[System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(190,158,88));$cream=[System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(246,239,222));$muted=[System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(184,190,198));$shadow=[System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(76,0,0,0));$pen=[System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(190,158,88),4);$g.FillRectangle($panel,80,78,1760,902);$g.DrawLine($pen,116,126,520,126);$g.DrawLine($pen,116,922,620,922);$img=[System.Drawing.Image]::FromFile($portrait);$g.DrawImage($img,[System.Drawing.Rectangle]::new(1210,130,540,735));$img.Dispose();$g.FillRectangle($shadow,1120,90,730,845);$fb=[System.Drawing.Font]::new('Georgia',[single]28,[System.Drawing.FontStyle]::Regular);$ft=[System.Drawing.Font]::new('Georgia',[single]54,[System.Drawing.FontStyle]::Bold);$fs=[System.Drawing.Font]::new('Georgia',[single]38,[System.Drawing.FontStyle]::Regular);$ff=[System.Drawing.Font]::new('Georgia',[single]28,[System.Drawing.FontStyle]::Regular);$g.DrawString('THE SAINTS',$fb,$gold,[single]116,[single]156);DrawWrapped $g $title.ToUpperInvariant() $ft $cream 116 355 17 66 4;DrawWrapped $g $sub $fs $muted 120 640 38 50 4;$g.DrawString($footer,$ff,$gold,[single]120,[single]944);$bmp.Save($out,[System.Drawing.Imaging.ImageFormat]::Png);$fb.Dispose();$ft.Dispose();$fs.Dispose();$ff.Dispose();$pen.Dispose();$shadow.Dispose();$panel.Dispose();$gold.Dispose();$cream.Dispose();$muted.Dispose();$g.Dispose();$bmp.Dispose()}
$count=0;$variant=0;foreach($scene in $plan.scenes){foreach($beat in $scene.beats){$portrait=$portraits[$variant%$portraits.Count];$out=Join-Path $assetDir ("scene_{0}_beat_{1}_image.png" -f $scene.scene_number,$beat.beat_id);$footer=if($beat.visual_type-match'monastery|location'){'Monastery, silence, and prayer'}elseif($beat.visual_type-match'manuscript|letter|book'){'Counsel, memory, and spiritual tradition'}else{'Witness, tradition, and grace'};NewCard $out $scene.title (Shorten $beat.narration_excerpt 145) $footer $portrait $variant;$count++;$variant++}}
Write-Output "Regenerated $count clean Saints beat cards without scene/beat debug labels."
