/** Minimal Saints editor: beat cards + scene audio -> MP4 + SRT. */
'use strict';
const fs=require('fs'); const path=require('path'); const { execSync }=require('child_process');
const { SAINTS_ROOT } = require('./channel_paths');
const ROOT=SAINTS_ROOT; const id=process.argv[2]; if(!id) throw new Error('Usage: node automation/saints_editor_agent.js <id>');
const scriptPath=path.join(ROOT,'scripts',`saints_video_${id}_data.js`); const assetDir=path.join(ROOT,'assets',`saints_video_${id}_assets`); const readyDir=path.join(ROOT,'videos','saints_ready'); const tmpDir=path.join(assetDir,'_render_tmp');
const ffmpeg=path.join(__dirname,'ffmpeg','bin','ffmpeg.exe'); const ffprobe=path.join(__dirname,'ffmpeg','bin','ffprobe.exe');
function sh(cmd){ execSync(cmd,{stdio:'inherit',windowsHide:true}); }
function out(cmd){ return execSync(cmd,{encoding:'utf8',windowsHide:true}).trim(); }
function q(p){ return '"'+String(p).replace(/"/g,'\\"')+'"'; }
function loadScript(){ const raw=fs.readFileSync(scriptPath,'utf8').replace(/^\uFEFF/,''); const m=raw.match(new RegExp(`window\\.SAINTS_SCRIPTS\\[${id}\\]\\s*=\\s*(\\{[\\s\\S]+\\})\\s*;?\\s*$`)); if(!m) throw new Error(`Could not parse Saints script ${id}`); return JSON.parse(m[1]); }
function dur(file){ return Number(out(`${q(ffprobe)} -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 ${q(file)}`)); }
function srtTime(sec){ const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=Math.floor(sec%60),ms=Math.floor((sec%1)*1000); return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')},${String(ms).padStart(3,'0')}`; }
function clean(t){ return String(t||'').replace(/<[^>]*>?/gm,' ').replace(/\s+/g,' ').trim(); }
function beatImages(n){ const re=new RegExp(`^scene_${n}_beat_.+_image\\.(png|jpg|jpeg)$`,'i'); if(!fs.existsSync(assetDir)) return []; return fs.readdirSync(assetDir).filter(x=>re.test(x)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(x=>path.join(assetDir,x)); }
function sceneImage(n){ for(const ext of ['png','jpg','jpeg']){ const p=path.join(assetDir,`scene_${n}_image.${ext}`); if(fs.existsSync(p)) return p; } return null; }
function main(){ if(!fs.existsSync(ffmpeg)||!fs.existsSync(ffprobe)) throw new Error('Missing local ffmpeg/ffprobe.'); fs.mkdirSync(readyDir,{recursive:true}); fs.rmSync(tmpDir,{recursive:true,force:true}); fs.mkdirSync(tmpDir,{recursive:true}); const script=loadScript(); const sceneVideos=[]; let srt=[]; let cursor=0; let idx=1;
for(const scene of script.scenes){ const n=scene.scene_number; const audio=path.join(assetDir,`scene_${n}_audio.wav`); if(!fs.existsSync(audio)) throw new Error(`Missing audio for scene ${n}: ${audio}`); let imgs=beatImages(n); if(!imgs.length){ const fallback=sceneImage(n); if(fallback) imgs=[fallback]; } if(!imgs.length) throw new Error(`Missing visuals for scene ${n}`); const ad=dur(audio); const segDur=Math.max(1,ad/imgs.length); const segs=[]; for(let i=0;i<imgs.length;i++){ const seg=path.join(tmpDir,`scene_${n}_${i}.mp4`); console.log(`Rendering Saints ${id} scene ${n} beat visual ${i+1}/${imgs.length}: ${segDur.toFixed(2)}s`); sh(`${q(ffmpeg)} -y -loop 1 -i ${q(imgs[i])} -t ${segDur.toFixed(3)} -vf "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,setsar=1" -r 30 -pix_fmt yuv420p -an ${q(seg)}`); segs.push(seg); }
const list=path.join(tmpDir,`scene_${n}_visuals.txt`); fs.writeFileSync(list,segs.map(p=>`file '${p.replace(/'/g,"'\\''")}'`).join('\n')); const visual=path.join(tmpDir,`scene_${n}_visual.mp4`); sh(`${q(ffmpeg)} -y -f concat -safe 0 -i ${q(list)} -c copy ${q(visual)}`); const sceneOut=path.join(tmpDir,`scene_${n}.mp4`); sh(`${q(ffmpeg)} -y -i ${q(visual)} -i ${q(audio)} -c:v copy -c:a aac -shortest ${q(sceneOut)}`); sceneVideos.push(sceneOut); srt.push(`${idx++}\n${srtTime(cursor)} --> ${srtTime(cursor+ad)}\n${clean(scene.voiceover)}\n`); cursor+=ad; }
const finalList=path.join(tmpDir,'final.txt'); fs.writeFileSync(finalList,sceneVideos.map(p=>`file '${p.replace(/'/g,"'\\''")}'`).join('\n')); const final=path.join(readyDir,`SAINTS_VIDEO_${id}_FINAL.mp4`); const srtFile=path.join(readyDir,`SAINTS_VIDEO_${id}_FINAL.srt`); sh(`${q(ffmpeg)} -y -f concat -safe 0 -i ${q(finalList)} -c copy ${q(final)}`); fs.writeFileSync(srtFile,srt.join('\n'),'utf8'); console.log(`Saints final video: ${final}`); console.log(`Saints captions: ${srtFile}`); console.log(`Duration: ${dur(final).toFixed(2)}s`); }
main();
