/** Sync Saints visual_plan.json with missing scenes from script. */
'use strict';
const fs=require('fs'); const path=require('path'); const { SAINTS_ROOT } = require('./channel_paths'); const ROOT=SAINTS_ROOT; const id=process.argv[2]; if(!id) throw new Error('Usage: node automation/saints_visual_plan_sync_agent.js <id>');
const scriptPath=path.join(ROOT,'scripts',`saints_video_${id}_data.js`); const assetDir=path.join(ROOT,'assets',`saints_video_${id}_assets`); const planPath=path.join(assetDir,'visual_plan.json');
function loadScript(){ const raw=fs.readFileSync(scriptPath,'utf8').replace(/^\uFEFF/,''); const m=raw.match(new RegExp(`window\\.SAINTS_SCRIPTS\\[${id}\\]\\s*=\\s*(\\{[\\s\\S]+\\})\\s*;?\\s*$`)); if(!m) throw new Error(`Could not parse Saints script ${id}`); return JSON.parse(m[1]); }
function loadAttributionMap(){ const attrPath=path.join(assetDir,'asset_attribution.json'); if(!fs.existsSync(attrPath)) return new Map(); const raw=JSON.parse(fs.readFileSync(attrPath,'utf8').replace(/^\uFEFF/,'')); const beats=Array.isArray(raw)?raw:(Array.isArray(raw.beats)?raw.beats:[]); return new Map(beats.filter(b=>b&&b.scene!=null&&b.beat_id!=null).map(b=>[`${b.scene}:${b.beat_id}`,b])); }
function excerpt(t,max=155){ const c=String(t||'').replace(/\s+/g,' ').trim(); return c.length<=max?c:c.slice(0,max).trim()+'...'; }
function chunks(t,count){ const s=String(t||'').split(/(?<=[.!?])\s+/).filter(Boolean); const g=Array.from({length:count},()=>[]); s.forEach((x,i)=>g[Math.min(count-1,Math.floor(i*count/Math.max(1,s.length)))].push(x)); return g.map(x=>x.join(' ')).filter(Boolean); }
function scenePlan(scene,start){ const parts=chunks(scene.voiceover,3); const duration=Math.max(36,Math.round(String(scene.voiceover||'').split(/\s+/).filter(Boolean).length/2.25)); const bd=Math.max(8,Math.round(duration/parts.length)); const beats=parts.map((part,idx)=>{ const suffix=String.fromCharCode(97+idx); const vt='icon_or_painting'; return {beat_id:`${scene.scene_number}${suffix}`,start_s:start+idx*bd,duration_s:idx===parts.length-1?Math.max(8,duration-bd*idx):bd,narration_excerpt:excerpt(part),visual_type:vt,asset_note:'Use only verified saint icon/portrait images. No monastery, manuscript, map, landscape, or generic source images.',primary_source_label:'Wikimedia Commons verified search',primary_source_url:`https://commons.wikimedia.org/w/index.php?search=${encodeURIComponent(scene.title+' orthodox saint public domain')}&title=Special:MediaSearch&type=image`,backup_source_url:'https://commons.wikimedia.org/',search_query:`${scene.title} orthodox saint public domain`,source_priority:2,asset_file:null,attribution_required:true,license_status:'verify_per_file_before_use',status:'pending',fallback:`scene_${scene.scene_number}_image.png`,suggested_filename:`beat_${scene.scene_number}${suffix}.jpg`}; }); return {scene_number:scene.scene_number,title:scene.title,start_s:start,duration_s:duration,beat_count:beats.length,visual_prompt:scene.visual_prompt,primary_asset_file:`scene_${scene.scene_number}_image.png`,beats}; }
function overlayAttribution(plan, attribution){ let synced=0; for(const scene of plan.scenes||[]){ for(const beat of scene.beats||[]){ const attr=attribution.get(`${scene.scene_number}:${beat.beat_id}`); if(!attr) continue; beat.asset_file=attr.asset_file||beat.asset_file; beat.primary_source_url=attr.source_url||beat.primary_source_url; beat.primary_source_label=attr.title||beat.primary_source_label; beat.license_status=attr.license||beat.license_status; beat.rights_status='verified'; beat.status='downloaded_verified'; beat.verified_source_key=attr.source_key||beat.verified_source_key; beat.attribution_required=Boolean(attr.license && !String(attr.license).startsWith('public_domain')); beat.visual_type=attr.visual_type||beat.visual_type; if(String(beat.visual_type).toLowerCase()==='icon_or_painting'){ beat.subject_framing=beat.subject_framing||'full_subject_contained'; beat.framing_qc=beat.framing_qc||'no_crop_contain_layout'; beat.layout_style=beat.layout_style||'left_text_right_saint'; } synced++; } } return synced; }
function main(){ if(!fs.existsSync(scriptPath)) throw new Error(`Missing script: ${scriptPath}`); fs.mkdirSync(assetDir,{recursive:true}); const script=loadScript(); const attribution=loadAttributionMap(); let plan=fs.existsSync(planPath)?JSON.parse(fs.readFileSync(planPath,'utf8').replace(/^\uFEFF/,'')):{channel:'The Saints',video_id:Number(id),title:script.video.title,niche:script.video.niche,generated_at:new Date().toISOString(),saint_target:script.video.title,scenes:[]}; const existing=new Set((plan.scenes||[]).map(s=>Number(s.scene_number))); let start=Math.max(0,...(plan.scenes||[]).map(s=>Number(s.start_s||0)+Number(s.duration_s||0))); let added=0; for(const scene of script.scenes||[]){ if(existing.has(Number(scene.scene_number))) continue; const sp=scenePlan(scene,start); plan.scenes.push(sp); start+=sp.duration_s; added++; } const synced=overlayAttribution(plan, attribution); plan.scenes.sort((a,b)=>Number(a.scene_number)-Number(b.scene_number)); plan.total_beats=plan.scenes.reduce((s,x)=>s+(x.beats?x.beats.length:0),0); plan.estimated_total_duration_s=plan.scenes.reduce((s,x)=>s+Number(x.duration_s||0),0); plan.generated_at=new Date().toISOString(); fs.writeFileSync(planPath,JSON.stringify(plan,null,2)); console.log(`Synced visual plan for Saints ${id}: added ${added} scene(s), ${synced} beat attribution overlays, ${plan.total_beats} beats total.`); }
main();

