/** Ensure queue entry for a Saints final video. */
'use strict';
const fs=require('fs'); const path=require('path'); const { REPO_ROOT, SAINTS_ROOT } = require('./channel_paths'); const ROOT=SAINTS_ROOT; const REPO=REPO_ROOT; const id=process.argv[2]; if(!id) throw new Error('Usage: node automation/saints_queue_entry_agent.js <id>');
const scriptPath=path.join(ROOT,'scripts',`saints_video_${id}_data.js`); const queuePath=path.join(ROOT,'metadata','queue.json');
function readJson(file,fallback){ if(!fs.existsSync(file)) return fallback; return JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,'')); }
function loadScript(){ const raw=fs.readFileSync(scriptPath,'utf8').replace(/^\uFEFF/,''); const m=raw.match(new RegExp(`window\\.SAINTS_SCRIPTS\\[${id}\\]\\s*=\\s*(\\{[\\s\\S]+\\})\\s*;?\\s*$`)); if(!m) throw new Error(`Could not parse Saints script ${id}`); return JSON.parse(m[1]); }
function chapters(scenes){ let total=0; return (scenes||[]).map(scene=>{ const words=String(scene.voiceover||'').split(/\s+/).filter(Boolean).length; const stamp=`${Math.floor(total/60)}:${String(Math.floor(total%60)).padStart(2,'0')}`; total+=Math.max(25,Math.round(words/2.25)); return {timestamp:stamp,title:scene.title,scene_number:scene.scene_number}; }); }
function main(){ if(!fs.existsSync(scriptPath)) throw new Error(`Missing script: ${scriptPath}`); fs.mkdirSync(path.dirname(queuePath),{recursive:true}); const script=loadScript(); const queue=readJson(queuePath,[]); const filename=`SAINTS_VIDEO_${id}_FINAL.mp4`; const entry={filename,source_path:`The Saints/videos/saints_ready/${filename}`,srt_filename:`SAINTS_VIDEO_${id}_FINAL.srt`,srt_source_path:`The Saints/videos/saints_ready/SAINTS_VIDEO_${id}_FINAL.srt`,thumbnail_filename:`Thumbnails/saints_video_${id}_generated_cinematic.png`,title:script.video.title,description:`${script.video.title}\n\nA reverent documentary from The Saints, framed through Christian witness, tradition, repentance, miracles, and grace.\n\nQuestion for viewers: what part of this story stayed with you most?`,tags:script.production_notes?.metadata_keywords||['The Saints','Orthodox saints','Christian monasticism'],category_id:'27',playlist_id:'PLlnXQFiTNjOvWHt1UhXy6r29kGtnOmDB4',status:'private',publish_days:[],publish_time:null,timezone:null,human_approval:false,channel:'The Saints',script_id:`saints_${id}`,chapters:chapters(script.scenes),pinned_comment:'What part of this saintly story stayed with you most?',watch_next_line:'If this story stayed with you, watch another life from The Saints next.',release_policy:'publish_immediately_when_ready'}; const existing=queue.find(x=>x.filename===filename); if(existing) Object.assign(existing,entry); else queue.push(entry); fs.writeFileSync(queuePath,JSON.stringify(queue,null,2)); console.log(`${existing?'Updated':'Created'} queue entry for ${filename}`); }
main();
